auth:
  enabled: true
  rootPassword: "1234"
  #existingSecret Existing secret with MongoDB (&reg;) credentials (keys: mongodb-passwords, mongodb-root-passi
  existingSecret: ""
architecture: replicaset 
replicaCount: 3
persistence:
  enabled: false
volumePermissions:
  enabled: false
metrics:
  enabled: false 
  prometheusRule:
    enabled: false
# bitnami/mongodb is not yet supported on ARM.
# Using unofficial tools to build bitnami/mongodb (arm64 support)
# more info: https://github.com/ZCube/bitnami-compat
#image:
# registry: ghcr.io/zcube
# repository: bitnami-compat/mongodb
#tag: 6.0.5
